#
# Copyright (c) 2020, 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
# Example 3
# Adds a separate application node running helidon app
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster-storage
spec:
  cluster: example-cluster
  jvm:
    memory:
      heapSize: 512m
    args:
      - "-Dcoherence.tracing.ratio=1"
      - "-DJAEGER_SERVICE_NAME=Coherence"
      - "-DJAEGER_ENDPOINT=http://10.96.91.223:14268/api/traces"
      - "-Dcoherence.distributed.asyncbackup=true"
  ports:
    - name: metrics
      port: 9612
      serviceMonitor:
        enabled: true
  coherence:
    cacheConfig: storage-cache-config.xml
    metrics:
      enabled: true
  image: tmiddlet/deployment-example:1.0.0
  imagePullPolicy: Always
  replicas: 2
---
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: example-cluster-rest
spec:
  cluster: example-cluster
  jvm:
    memory:
      heapSize: 512m
    args:
      - "-Dcoherence.tracing.ratio=1"
      - "-DJAEGER_SERVICE_NAME=Coherence"
      - "-DJAEGER_ENDPOINT=http://10.96.91.223:14268/api/traces"
      - "-Dcoherence.distributed.asyncbackup=true"
  ports:
    - name: metrics
      port: 9612
      serviceMonitor:
        enabled: true
    - name: http
      port: 8080
  coherence:
    cacheConfig: storage-cache-config.xml
    storageEnabled: false
    metrics:
      enabled: true
  image: tmiddlet/deployment-example:1.0.0
  imagePullPolicy: Always
  application:
    main: com.oracle.coherence.examples.Main
  replicas: 1
